---
title: "stacas"
author: "Julia Zhong"
date: today
format:
  html:
    toc: true
    page-layout: full
    embed-resources: true
    code-fold: true
    code-tools: true
    link-external-newwindow: true
lightbox:
  match: auto
  effect: zoom
  desc-position: right
execute:
  warning: false
from: markdown+emoji 
editor_options: 
  chunk_output_type: console
---

## STACAS Data Integration

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r, message=FALSE}
if (!require("remotes", quietly = TRUE))
    install.packages("remotes")
library(remotes)

if (!requireNamespace("STACAS", quietly = TRUE))
  remotes::install_github("carmonalab/STACAS")

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(c("LoomExperiment", "SingleCellExperiment"))
```

```{r}
library(anndata)
library(dplyr)
library(ggplot2)
library(reticulate)
library(schard)
library(Seurat)
library(sceasy)
library(STACAS)

use_condaenv('DAL')

seed = 1234
set.seed(seed)
```

```{r}
ad <- read_h5ad("adata_2apr2025.h5ad")
ad
```

convert AnnData object to Seurat object

```{r}
# sceasy::convertFormat('adata.h5ad', from="anndata", to="seurat", outFile='seurat.rds')
```

```{r}
# object <- readRDS('seurat.rds')
object = schard::h5ad2seurat('adata_2apr2025.h5ad', use.raw=TRUE)
```

```{r}
nfeatures <- 1000
ndim <- 20
object <- FindVariableFeatures(object, nfeatures = nfeatures) %>%
  NormalizeData() %>% ScaleData() %>%
  RunPCA(npcs=ndim) %>% RunUMAP(dims=1:ndim)
```

```{r}
pre <- DimPlot(object, group.by = "sample") + theme(aspect.ratio = 1) +
  ggtitle("Dataset/batch before integration")

pre
```

```{r}
object_integrated <- object %>% SplitObject(split.by = "sample") %>%
      Run.STACAS(dims = 1:ndim, anchor.features = nfeatures) %>%
      RunUMAP(dims = 1:ndim) 

post <- DimPlot(object_integrated, group.by = "sample")

post
```

```{r}
post <- DimPlot(object_integrated, group.by = "sample") + theme(aspect.ratio = 1) +
  ggtitle("Dataset/batch after integration")

pre | post
```

```{r}
DimPlot(object, group.by = "sample", split.by = "sample") + theme(aspect.ratio = 1) +
  ggtitle("Dataset/batch before integration")
```

```{r}
DimPlot(object_integrated, group.by = "sample", split.by = "sample") + theme(aspect.ratio = 1) +
  ggtitle("Dataset/batch after integration") 
```

+ coord_fixed(ratio = 0.01) figure out how to get the spacing right lol
